In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/naukri_data_science_jobs_india.csv")

In [3]:
df.head()

,Company,Location,education,Skills/Description,job_type,salary,Job Experience,Job_Role
0,UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",Post-graduate,"python, MLT, statistical modeling, machine lea...",contract,939957.0,5-6,Senior Data Scientist
1,Walmart,Bangalore/Bengaluru,Post-graduate,"Data Science, Machine learning, Python, Azure,...",contract,2060767.0,1-7,Senior Data Scientist
2,SAP India Pvt.Ltd,Bangalore/Bengaluru,UG,"Python, IT Skills, Testing, Cloud, Product Man...",full-time,698970.0,7-8,Applied Data Scientist / ML Senior Engineer (P...
3,UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",Post-graduate,"python, machine learning, Data Science, data a...",full-time,529674.0,6-7,Data Scientist
4,Walmart,Bangalore/Bengaluru,UG,"IT Skills, Python, Data Science, Machine Learn...",contract,2163829.0,3-7,Data Scientist

In [4]:
df.tail()

,Company,Location,education,Skills/Description,job_type,salary,Job Experience,Job_Role
11995,Krazy Mantra HR Solutions Pvt. Ltd,"Kolkata, Chennai, Bangalore/Bengaluru",Post-graduate,"Spark, Python, S3, lambda, Athena, AWS, IT Ski...",full-time,2041019.0,0-5,Tech Lead/Architect ( Contractual )
11996,cliqhr.com,"Hyderabad/Secunderabad, Pune, Bangalore/Bengaluru",Post-graduate,"AirFlow, BigQuery, GCS, Kafka, Java, Shell scr...",contract,783683.0,6-8,Tech Lead / POD Lead
11997,Serving Skill,"Hyderabad/Secunderabad, Bangalore/Bengaluru",Post-graduate,"IT Skills, Java, Software Development, Testing...",full-time,2386372.0,1-7,Java Full Stack Developer - Hibernate / Spring
11998,cliqhr.com,"Kochi/Cochin, Mumbai, Hyderabad/Secunderabad, ...",Post-graduate,"PowerShell, Azure Data Factory, Azure, PaaS, M...",contract,929479.0,2-6,Tech Lead - Azure
11999,Huquo Consulting Pvt. Ltd,Bangalore/Bengaluru,Under-graduate,"Java, JavaScript, Machine Learning, NoSQL, Clo...",contract,1331813.0,0-3,Full Stack Developer - Machine Learning

In [5]:
df.shape

(12000, 8)

In [6]:
df.columns

Index(['Company', 'Location', 'education', 'Skills/Description', 'job_type',
       'salary', 'Job Experience', 'Job_Role'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Company             12000 non-null  str
 1   Location            12000 non-null  str
 2   education           10324 non-null  str
 3   Skills/Description  12000 non-null  str
 4   job_type            10720 non-null  str
 5   salary              11024 non-null  float64
 6   Job Experience      12000 non-null  str
 7   Job_Role            12000 non-null  str
dtypes: float64(1), str(7)
memory usage: 750.1 KB

In [8]:
df.describe(include="all")

,Company,Location,education,Skills/Description,job_type,salary,Job Experience,Job_Role
count,12000,12000,10324,12000,10720,1.102400e+04,12000,12000
unique,3507,822,6,11356,2,NaN,30,6563
top,Accenture,Bangalore/Bengaluru,UG,Data Scientist,contract,NaN,7-8,Data Engineer
freq,490,3383,1757,8,5366,NaN,1464,580
mean,NaN,NaN,NaN,NaN,NaN,1.410455e+06,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,6.382235e+05,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,3.000220e+05,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,8.637465e+05,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,1.414624e+06,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,1.966901e+06,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,2.499934e+06,NaN,NaN

In [9]:
df.sample(5)

,Company,Location,education,Skills/Description,job_type,salary,Job Experience,Job_Role
11982,Serving Skill,Bangalore/Bengaluru,NaN,"Java, Hibernate, Full Stack, MySQL, Javascript...",full-time,1056941.0,0-7,Java Full Stack Developer - Hibernate/ Spring
6782,NOTUS SERVICES PRIVATE LIMITED,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",NaN,"BigQuery, Dataflow, SQL, Dataproc, Firebase, C...",contract,1909224.0,0-5,GCP Data Engineer
5716,Innova Solutions Private Limited,Chennai,PG,"docker, EMR, Airflow, Python, Pyspark, AWS, IT...",full-time,760197.0,5-7,Innova Hiring Data Engineer @ Chennai
11279,STEELMINT,"Jaipur, Raipur",NaN,"excel, secondary research, investor relations,...",contract,2233147.0,2-4,Market Analyst (Male/ Female)
8678,Gruppent Solutions Pvt. Ltd.,Kolkata,Post-graduate,"BPO, data analysis, Analytical skills, Call mo...",contract,2031795.0,6-8,Quality Analyst

In [10]:
df.isnull().sum()

Company                  0
Location                 0
education             1676
Skills/Description       0
job_type              1280
salary                 976
Job Experience           0
Job_Role                 0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.nunique()

Company                3507
Location                822
education                 6
Skills/Description    11356
job_type                  2
salary                10990
Job Experience           30
Job_Role               6563
dtype: int64